### ISSUE TITLE
evolution and backward/forward compatibility 

### ISSUE THREAD

**Issue by elf-pavlik** [w3c-social/social-arch#2]
People often emphasize graceful way of how The Web evolves. One example to showcase that

1) Using latest browser visit page authored 15 years ago
2) Using very old browser e.g. Mosaic2 visit page authored in last days
### TODO
- [ ] research AS2.0 braking compatibility with AS1.0
- [ ] research promises of REST in that field
- [ ] research evolution of JSON-LD contexts (v1, v2 ?)

**Comment by dret** [comment]
the REST community does have an extensive body of research and experience in that field. it comes down to a combination of openness, extensibility, and a well-defined processing model, so that all possible combinations of "version mismatches" (old consumers of new services and new consumers of old services are the two tricky ones, as mentioned in the issue) work well. various strategies have been used (mustIgnore and mustUnderstand are two popular ones), and they all come with different capabilities, constraints, and side-effects.
