### ISSUE TITLE
automated form generation

### ISSUE THREAD

**Issue by elf-pavlik** [w3c-social/social-arch#3]
Modern applications often render forms. Hypermedia APIs also need ways to describe expected inputs. Many efforts exist nowadays but no standard yet to address it.
### See also
- https://twitter.com/SocialWebWG/status/527499121725157376
### TODO
- [ ] research [Data Shapes](http://www.w3.org/2014/data-shapes/wiki/Main_Page)
- [ ] research [Schema.org Potential Action](http://schema.org/docs/actions.html)
- [ ] research [Hydra API](http://www.hydra-cg.com/spec/latest/core/#documenting-a-web-api)
- [ ] research [ActivityStreams 2.0: Actions Handlers](http://elf-pavlik.github.io/w3c-socialwg-activitystreams/activitystreams2-actions.html)

**Comment by dret** [comment]
URI templates http://tools.ietf.org/html/rfc6570 are one possible foundation, even though they are only part of a solution. @mamund's UBER https://github.com/mamund/media-types/blob/master/uber-hypermedia.asciidoc and my own link descriptions http://tools.ietf.org/html/draft-wilde-link-desc are attempts and bridging the gap between RFC 6570 and associating template variables with concepts. of course this is all about the "machine form" idea and not so much about the HTML-ish notion of UIs for form data.
at https://github.com/dret/hyperpedia i am in the process of describing general hypermedia concepts (https://github.com/dret/hyperpedia/blob/master/concepts.md#traversal-hints is where i am covering forms under the general concept of "traversal hints"), so maybe that's a good opportunity to look at some formats in more detail and see if and how they do provide sufficient information so that link traversal can include form-like interaction semantics.
